return {
	servers = {
		"rust_analyzer",
		"pyright",
		"tsserver",
		"gopls",
		"golangci_lint_ls",
		"eslint",
		-- "cmake",
		"cssmodules_ls",
		"stylelint_lsp",
		"dockerls",
		"docker_compose_language_service",
		-- "marksman",
		-- "svelte",
		-- "clangd",
		"cssls",
		"taplo",
		"angularls",
		"lua_ls",
		"jsonls",
		"bufls",
		"html",
		-- "tailwindcss",
	},
	tools = {
		-- formatters
		-- "clang-format",
		"prettier",
		-- "prettierd",
		"goimports",
		"gofumpt",
		-- "golines",
		"rustfmt",
		"stylua",
		"buf",
		"autopep8",
		-- linters
		"pylint",
		-- "eslint_d",
		"staticcheck",
		"golangci-lint", -- for golangci-lint-lsp
	},
}
