return {
    "rust_analyzer",
    "pyright",
    "tsserver",
    "gopls",
    -- "golangci_lint_ls",
    "eslint",
    -- "cmake",
    "cssmodules_ls",
    "stylelint_lsp",
    "dockerls",
    "docker_compose_language_service",
    -- "marksman",
    -- "svelte",
    -- "clangd",
    "cssls",
    "taplo",
    "angularls",
    "lua_ls",
    "jsonls",
    "bufls",
    "html",
    -- "tailwindcss",
}
